name: "Issue assigner"

on: [issues, issue_comment]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Bugheist/issue-assigner@main
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
